version: '3.9'

services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: navystack/nodebb:3.6.6
    depends_on:
      - postgres
    volumes:
      - ./setup.json:/usr/src/app/setup.json
      - nodebb-config:/opt/config
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-modules:/usr/src/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.services.nodebb.loadbalancer.server.port=4567'
      - 'traefik.http.services.nodebb.loadbalancer.passhostheader=true'
      - 'traefik.http.routers.nodebb-rt.entrypoints=websecure'
      - 'traefik.http.routers.nodebb-rt.rule=Host(`navystack.com`) || Host(`www.navystack.com`)'
      - 'traefik.http.routers.nodebb-rt.service=nodebb'
      - 'traefik.http.routers.nodebb-rt.middlewares=www-to-Root@file, security-headers@file, websocket@file'
      - 'traefik.http.routers.nodebb-rt.tls=true'
    networks:
      - traefik-network
      - interanl

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodebb
      POSTGRES_PASSWORD: VKSl2cYx7kD8hSL2s42xuDT7vqYDVp
      POSTGRES_DB: nodebb
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    networks:
      - interanl

volumes:
  pgsql-data:
  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/
  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./build/
  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./uploads/
  nodebb-modules:

networks:
  traefik-network:
    external: true
  interanl:
