services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: navystack/nodebb:latest
    volumes:
      - ./setup.json:/usr/src/app/setup.json
      - nodebb-config:/opt/config
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-modules:/usr/src/app/node_modules
    environment:
      OVERRIDE_UPDATE_LOCK: true
    networks:
      - internal

  nginx:
    container_name: nginx-nodebb
    image: navystack/openresty:1.25.3
    logging:
      driver: json-file
      options:
        tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
        max-size: '10m'
        max-file: 100
    restart: unless-stopped
    volumes:
      - nodebb-build:/usr/share/nginx/build
      - nodebb-uploads:/usr/share/nginx/public/uploads
      - ./nginx:/etc/nginx/conf.d/
      # - ./nginx-etc/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    networks:
      - internal
      - traefik-network
    depends_on:
      - nodebb
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.services.navystack.loadbalancer.server.port=80'
      - 'traefik.http.services.navystack.loadbalancer.passhostheader=true'
      - 'traefik.http.routers.navystack.entrypoints=websecure'
      - 'traefik.http.routers.navystack.rule=Host(`navystack.com`) || Host(`www.navystack.com`)'
      - 'traefik.http.routers.navystack.service=navystack'

  mongo:
    container_name: mongo
    image: mongo:7.0-jammy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: navystack-mongo
      MONGO_INITDB_ROOT_PASSWORD: oVvzozYfCgZXJ7373Y9VvmXh0J8WyF
      MONGO_INITDB_DATABASE: navystack-mongo
    volumes:
      - mongo-data:/data/db
      - ./nodebb-mongo-init.js:/docker-entrypoint-initdb.d/user-init.js
    networks:
      - internal

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: navystack-mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: xMxK4JX2GINcIUYKnLVFbUOq0WeqbB
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - internal

  redis:
    container_name: redis
    image: redis:7-bookworm
    restart: unless-stopped
    volumes:
      - ./.docker/database/redis:/data
    networks:
      - internal

volumes:
  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/

  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./build/

  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./uploads/

  nodebb-modules:
  mongo-data:

networks:
  traefik-network:
    external: true
  internal:
