services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: ghcr.io/3Base-Labs/nodebb-docker:latest
    volumes:
      - ./setup.json:/usr/src/app/setup.json
      - nodebb-config:/opt/config
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-modules:/usr/src/app/node_modules
    environment:
      OVERRIDE_UPDATE_LOCK: true
    ports:
      - 4567:4567
    networks:
      - internal

  mongo:
    container_name: mongo
    image: mongo:7.0-jammy
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: navystack-mongo
      MONGO_INITDB_ROOT_PASSWORD: oVvzozYfCgZXJ7373Y9VvmXh0J8WyF
      MONGO_INITDB_DATABASE: navystack-mongo
    volumes:
      - mongo-data:/data/db
      - ./nodebb-mongo-init.js:/docker-entrypoint-initdb.d/user-init.js
    networks:
      - internal

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: navystack-mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: oVvzozYfCgZXJ7373Y9VvmXh0J8WyF
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - internal

  redis:
    container_name: redis
    image: redis:7-bookworm
    restart: unless-stopped
    volumes:
      - ./.docker/database/redis:/data
    networks:
      - internal

volumes:
  nodebb-config:
  nodebb-build:
  nodebb-uploads:
  nodebb-modules:
  mongo-data:

networks:
  traefik-network:
    external: true
  internal:
