version: '3.9'

services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: navystack/nodebb:3.6.5
    volumes:
      - nodebb-data:/usr/src/app
    environment:
      CONFIG_DIR: /usr/src/app

    networks:
      - traefik-network
      - interanl
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"

      - "traefik.http.services.nodebb.loadbalancer.server.port=4567"
      - "traefik.http.services.nodebb.loadbalancer.passhostheader=true"

      - "traefik.http.routers.nodebb-rt.entrypoints=websecure"
      - "traefik.http.routers.nodebb-rt.rule=Host(`example.com`) || Host(`www.example.com`)"
      - "traefik.http.routers.nodebb-rt.service=nodebb"
      - "traefik.http.routers.nodebb-rt.middlewares=www-to-Root@file, security-headers@file, websocket@file"
      - "traefik.http.routers.nodebb-rt.tls=true"
      - "traefik.http.routers.nodebb-rt.tls.certresolver=letsencrypt"

  mongo:
    container_name: mongo
    image: navystack/nodebb:mongo7-latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: nodebb
      MONGO_INITDB_DATABASE: nodebb
    volumes:
      - mongo-data:/data/db
      - ./nodebb-mongo-init.js:/docker-entrypoint-initdb.d/user-init.js
    networks:
      - interanl

volumes:
  nodebb-data:
  mongo-data:

networks:
  traefik-network:
    external: true
  interanl:
