name: Check for updates

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Versions
        id: check_versions
        run: |
          LOCAL_VER=$(git -c 'versionsort.suffix=-' \
              ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/3base-labs/nodebb-docker.git \
              | tail --lines=1 \
              | cut --delimiter='/' --fields=3)
          RELEASE_VER=$(git -c 'versionsort.suffix=-' \
              ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/NodeBB/NodeBB.git \
              | tail --lines=1 \
              | cut --delimiter='/' --fields=3)
          echo "LOCAL_VER=$LOCAL_VER" >> $GITHUB_ENV
          echo "RELEASE_VER=$RELEASE_VER" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VER }}
          release_name: Release ${{ env.RELEASE_VER }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
        if: env.RELEASE_VER != env.LOCAL_VER
